### ISSUE TITLE
Infinite Loop on SAML call

### ISSUE THREAD

**Issue by Viniciuslfta** [SAP/abap-alv-google-upload-sheet#18]
![image](https://user-images.githubusercontent.com/3707682/183497614-47a7ab94-1fbc-4d8b-9cf4-9a37f8a18be1.png)

When generating refresh token with SSO, it enters an infinite loop, this error has happened on other SAP tools, is there a way to fix it on SAP ABAP?

We're facing the same error below but on ABAP:
https://github.com/SAP/spartacus/issues/11465

**Comment by SAPSM** [comment]
Hi Viniciuslfta,

Since this seems, judging from your description, like a general issue in the OAuth 2 framework and not directly related to the provided integration, please file an incident on SAP component **BC-SEC-LGN-OA2** describing your case in detail so colleagues can reproduce it.

Kind Regards,
Sebastian
