### ISSUE TITLE
Unable to Authenticate via SSO when Web Dispatcher/Load Balancer enabled.

### ISSUE THREAD

**Issue by jdegrandchamp89** [SAP/abap-alv-google-upload-sheet#6]
When trying to use the Google Sheet Export functionality in production system using SSO when do not get to the Google Auth screen, without entering an SAP Manual Login password. This is OK for technical users but for typical end users this is not a viable solution. Wondering if there is any documentation available for how to get this to work with SSO setup enabled for SAP?

[Error Replication Steps in QAT vs Prod.pdf](https://github.com/SAP-samples/abap-alv-google-upload-sheet/files/4262336/Error.Replication.Steps.in.QAT.vs.Prod.pdf)

**Comment by KDS42** [comment]
According to the description in the attached PDF the OAuth call starts a loop that continually loops through different URLs. This should be fixed by note https://launchpad.support.sap.com/#/notes/2894424 .

The logon prompt during start of the export to Google sounds like a problem with the configuration of the authentication method. It depends which method is used (maybe SAML). To further analyze it - please open an SAP incident - with the reference link to this issue.

**Comment by KDS42** [comment]
Component BC-SRV-ALV
